<a href="https://colab.research.google.com/github/Devsah9051/Credit-Card-Fraud-Detection-/blob/main/credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING THE MAIN LIBRARIES

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# read the content from csv file here
df =pd.read_csv('/content/creditcard.csv.zip')

In [ ]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,'0'
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,'0'
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,'0'
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,'0'
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,'0'

In [ ]:
# it is the shape of dataset
df.shape

(284807, 31)

In [ ]:
# Number of columns here:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [ ]:
#infromation :
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  object
dtypes: float64(30), object(1)
memory usage: 67.4+ MB

#here checking the credit card trasation is valid or not :
#0 stands for lagit transation
#1 stands for invalid transation

In [ ]:
# checking number of 0 and 1 in class:
df['Class'].value_counts().astype(int)

Class
'0'    284315
'1'       492
Name: count, dtype: int64

In [ ]:
# here checking the missing values :
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
#here i converting the '0' into integer :
df['Class'] = df['Class'].astype(str).str.replace("'", "").astype(int)

In [ ]:
#placing the legit & fraud  value in differentr variable :
legit=df[df.Class==0]
fraud=df[df.Class==1]

print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [ ]:
#statistical measures
print(legit.Amount.describe())
print('*'*20)
print('*'*20)
print(fraud.Amount.describe())

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64
********************
********************
count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [ ]:
# compair the values here:\
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [ ]:
# deling the data using undersampling here :

legit_sample=legit.sample(n=492)

new_df=pd.concat([legit_sample,fraud],axis=0)

In [ ]:
print(new_df.shape)

(984, 31)

In [ ]:
#here new dataset head:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
173258,121408.0,2.302563,-1.162678,-1.328746,-1.788156,-0.726987,-0.521557,-0.880395,-0.223388,-1.977647,...,0.146769,0.916456,0.095295,0.750564,0.086922,0.024060,-0.007186,-0.061959,7.85,0
120675,75919.0,-0.454909,0.264624,2.237498,1.296033,-0.453957,0.784885,-0.034307,0.231624,0.672313,...,0.198828,0.985035,-0.164058,-0.051799,-0.103707,-0.118305,0.237499,0.179627,64.00,0
201240,133791.0,-7.035087,-8.483067,-3.915746,-0.103232,4.666024,-4.630918,-0.305551,-0.409451,0.823101,...,0.416707,0.772694,-1.937941,-0.088960,-1.482170,0.488720,1.477022,-1.617020,483.00,0
182919,125584.0,-0.555637,0.831301,-0.772359,0.127699,2.268730,-0.948491,1.290902,-0.102018,-0.860211,...,0.199591,0.513175,-0.131461,0.579922,-0.138248,-0.774134,0.182471,0.246832,15.66,0
1574,1230.0,-0.714882,1.104335,1.316765,-0.325951,0.309748,0.065227,0.513877,0.239953,-0.468773,...,-0.200637,-0.437641,-0.041606,-0.325900,-0.197367,0.108175,0.390326,0.161835,5.55,0

In [ ]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [ ]:
# new statsitical measure:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96774.786585,-0.034387,0.026414,-0.046729,-0.074073,-0.041117,-0.015264,0.116628,-0.000913,-0.049237,...,-0.024063,0.025656,0.031031,-0.009625,-0.000177,0.012249,0.013145,-0.004640,-0.003651,99.492846
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [ ]:
# spliting the data from here:
from sklearn.model_selection import train_test_split

In [ ]:
X=new_df.drop(columns='Class',axis=1)
Y=new_df['Class']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20,stratify=Y, random_state=42)
print(X.shape,X_train.shape,X_test.shape)


from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

(984, 30) (787, 30) (197, 30)

In [ ]:
# model traing here:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
model={
    'LogisticRegression':LogisticRegression(),
    'RandomForestClassifier':RandomForestClassifier(n_estimators=100,
    max_depth=10)
}

from sklearn.metrics import classification_report,accuracy_score
for name,m in model.items():
  print(f"model:{name}")
  m.fit(X_train,y_train)
  y_pred=m.predict(X_test)
  print(classification_report(y_test,y_pred))
  print("*"*50)

model:LogisticRegression
              precision    recall  f1-score   support

           0       0.95      0.98      0.97        99
           1       0.98      0.95      0.96        98

    accuracy                           0.96       197
   macro avg       0.96      0.96      0.96       197
weighted avg       0.96      0.96      0.96       197

**************************************************
model:RandomForestClassifier
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        99
           1       0.97      0.95      0.96        98

    accuracy                           0.96       197
   macro avg       0.96      0.96      0.96       197
weighted avg       0.96      0.96      0.96       197

**************************************************

In [ ]:
# testing my model on random data :
input_data= X_test[0]

#convert into array:
input_data=np.array(input_data).reshape(1,-1)

#scaling if it needed :
input_data=scaler.transform(input_data)

try:
    input_data = scaler.transform(input_data)
except:
    pass

# Select a specific model from the dictionary for prediction
# For example, using the RandomForestClassifier:
prediction = model['RandomForestClassifier'].predict(input_data)

if prediction[0]==0:
  print('valid transaction')
else:
  print('invalid transaction')

valid transaction

In [ ]:
# saving the model here:
import joblib
joblib.dump(model['RandomForestClassifier'],'credit_card_model.pkl')
joblib.dump(scaler,'scaler.pkl')
joblib.dump(X.columns.tolist(),'columns.pkl')

['columns.pkl']